auto:
  hosts: AUTO_HOSTS
  hosts_gentle: AUTO_GENTLE_HOSTS
  cfs: AUTO_CFS
  dfs: AUTO_DFS
sshfs_path: "SSHFS_PATH"
remote_user: "REMOTE_USER"
remote_dir: "REMOTE_DIR"
pem_file:
  default: "PEM_FILE"
instances:
  default:
    iid: "IID"
    domains:
      - "DOMAIN"
